spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/mynews
spring.datasource.username=postgres
spring.datasource.password=postgres
mybatis.mapper-locations=classpath*:mapper/*.xml
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB